services:
  - type: web
    name: stock-market-analytics
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    envVars:
      - key: VITE_GOOGLE_API_KEY
        # Add your secret from Render.com dashboard
        sync: false
    pullRequestPreviewsEnabled: true
    autoDeploy: true
