services:
  - type: web
    name: stock-market-analytics
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm install -g serve && serve -s dist -p $PORT
    autoDeploy: true
    envVars:
      - key: VITE_GOOGLE_API_KEY
        sync: false
      - key: NODE_VERSION
        value: 18.17.0
