services:
  - type: web
    name: stock-market-analytics
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
    envVars:
      - key: VITE_GOOGLE_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
